### ISSUE TITLE
Train split 时候报错

### ISSUE THREAD

**Issue by rogerus** [WangRongsheng/MedQA-ChatGLM#3]
```
05/16/2023 13:54:41 - INFO - datasets.builder - Generating train split
Generating train split: 0 examples [00:00, ? examples/s]05/16/2023 13:54:44 - ERROR - datasets.packaged_modules.json.json - Failed to read file '/root/.cache/huggingface/datasets/downloads/13b7313f9ce080a2697c9d786e3007888f44a89cdeab298bb587b2255a14216e' with error <class 'AttributeError'>: 'list' object has no attribute 'keys'
Traceback (most recent call last):                      
  File "/root/autodl-tmp/MedQA-ChatGLM/med_venv/lib/python3.10/site-packages/datasets/builder.py", line 1858, in _prepare_split_single
    for _, table in generator:
  File "/root/autodl-tmp/MedQA-ChatGLM/med_venv/lib/python3.10/site-packages/datasets/packaged_modules/json/json.py", line 146, in _generate_tables
    raise ValueError(f"Not able to read records in the JSON file at {file}.") from None
ValueError: Not able to read records in the JSON file at /root/.cache/huggingface/datasets/downloads/13b7313f9ce080a2697c9d786e3007888f44a89cdeab298bb587b2255a14216e.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/MedQA-ChatGLM/MedQA-ChatGLM/finetune.py", line 88, in <module>
    main()
  File "/root/autodl-tmp/MedQA-ChatGLM/MedQA-ChatGLM/finetune.py", line 22, in main
    dataset = prepare_data(model_args, data_args)
  File "/root/autodl-tmp/MedQA-ChatGLM/MedQA-ChatGLM/utils/common.py", line 309, in prepare_data
    raw_datasets = load_dataset(dataset_info.dataset_name, cache_dir=model_args.cache_dir)
  File "/root/autodl-tmp/MedQA-ChatGLM/med_venv/lib/python3.10/site-packages/datasets/load.py", line 1797, in load_dataset
    builder_instance.download_and_prepare(
  File "/root/autodl-tmp/MedQA-ChatGLM/med_venv/lib/python3.10/site-packages/datasets/builder.py", line 890, in download_and_prepare
    self._download_and_prepare(
  File "/root/autodl-tmp/MedQA-ChatGLM/med_venv/lib/python3.10/site-packages/datasets/builder.py", line 985, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/root/autodl-tmp/MedQA-ChatGLM/med_venv/lib/python3.10/site-packages/datasets/builder.py", line 1746, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/root/autodl-tmp/MedQA-ChatGLM/med_venv/lib/python3.10/site-packages/datasets/builder.py", line 1891, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
```
下载完dataset以后一开始split就报错。看了下下载到的dataset的jsonl文件，里面全部都是unicode转义符，或许是跟这个有关？
代码commit id：`0a08f1ec708293922e137c93aa587455321c2808`

**Comment by WangRongsheng** [comment]
可以贴一下训练代码，我看下

**Comment by XiudingCai** [comment]
> 可以贴一下训练代码，我看下

一样的，使用readme提供的训练脚本，运行到split的时候，就报错了。平台同样是windows
